services:
  db:
    image: postgres:13.15
    restart: unless-stopped
    env_file:
      - .env
    #ports:
    #  - 127.0.0.1:5433:5432
    #ports:
    #  - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dokploy-network

  hr-tools-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    #container_name: hr-tools-backend
    depends_on:
      - db
      - minio
    ports:
      - 8080:8080
    #expose:
    #  - "8080"
      #- "30128:8080"
    networks:
      - dokploy-network
  minio:
    image: docker.io/bitnami/minio:2024.11.7
    expose:
      - "9000"
      - "9001"
    volumes:
      - 'minio_data:/data'
    env_file:
      - .env
    networks:
      - dokploy-network

  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - hr-tools-backend
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/
  #   networks:
  #     - backend
networks:
  dokploy-network:
    external: true

volumes:
  db-data: {}
  minio_data: {}
