services:
  db:
    image: postgres:13.15
    restart: unless-stopped
    env_file:
      - env
    #ports:
    #  - 127.0.0.1:5433:5432
    #ports:
    #  - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  hr-tools-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-tools-backend
    depends_on:
      - db 
    env_file:
      - env
    ports:
      - 127.0.0.1:8080:8080
      #- "30128:8080"
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - hr-tools-backend 
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/
      
volumes:
  db-data: {}