services:
  db:
    image: postgres:13.15
    restart: unless-stopped
    env_file:
      - env
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  hr-tools-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-tools-backend
    env_file:
      - env
    ports:
      - 127.0.0.1:8080:8080

volumes:
  db-data: