definitions:
  adminpanelapimodels.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role:
        $ref: '#/definitions/models.UserRole'
    type: object
  adminpanelapimodels.UserID:
    properties:
      id:
        type: string
    type: object
  adminpanelapimodels.UserUpdate:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role:
        $ref: '#/definitions/models.UserRole'
    type: object
  adminpanelapimodels.UserView:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_login:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role:
        $ref: '#/definitions/models.UserRole'
    type: object
  apimodels.Response:
    properties:
      data:
        description: данные ответа
      message:
        description: сообщение ошибки
        type: string
      status:
        description: результат обработки fail/success
        type: string
    type: object
  authapimodels.JWTRefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  authapimodels.JWTResponse:
    properties:
      refresh_token:
        type: string
      token:
        type: string
    type: object
  authapimodels.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  authapimodels.SendEmail:
    properties:
      email:
        description: Почта, на которую надо отправить письмо с подтверждением
        type: string
    type: object
  models.UserRole:
    enum:
    - SUPER_ADMIN
    type: string
    x-enum-varnames:
    - UserRoleSuperAdmin
  spaceapimodels.CreateAdmin:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  spaceapimodels.CreateOrganization:
    properties:
      admin_data:
        $ref: '#/definitions/spaceapimodels.CreateAdmin'
      director_name:
        type: string
      full_name:
        type: string
      inn:
        type: string
      kpp:
        type: string
      ogrn:
        type: string
      organization_name:
        type: string
      organization_type:
        type: string
    type: object
  spaceapimodels.SpaceUser:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_admin:
        type: boolean
      last_name:
        type: string
      phone_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/admin_panel/login:
    post:
      description: Аутентификация пользователя
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authapimodels.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apimodels.Response'
            - properties:
                data:
                  $ref: '#/definitions/authapimodels.JWTResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Аутентификация пользователя
      tags:
      - Админ панель
  /api/v1/admin_panel/user/create:
    post:
      description: Создание пользователя
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/adminpanelapimodels.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodels.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Создание пользователя
      tags:
      - Админ панель. Пользователи
  /api/v1/admin_panel/user/delete:
    delete:
      description: Удаление пользователя
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/adminpanelapimodels.UserID'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodels.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Удаление пользователя
      tags:
      - Админ панель. Пользователи
  /api/v1/admin_panel/user/get/{userID}:
    get:
      description: Получение пользователя
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: user ID
        in: path
        name: userID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apimodels.Response'
            - properties:
                data:
                  $ref: '#/definitions/adminpanelapimodels.UserView'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Получение пользователя
      tags:
      - Админ панель. Пользователи
  /api/v1/admin_panel/user/list:
    post:
      description: Получение списка пользователей
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apimodels.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/adminpanelapimodels.UserView'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Получение списка пользователей
      tags:
      - Админ панель. Пользователи
  /api/v1/admin_panel/user/update:
    put:
      description: Изменение пользователя
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/adminpanelapimodels.UserUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodels.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Изменение пользователя
      tags:
      - Админ панель. Пользователи
  /api/v1/auth/check-email:
    post:
      description: Проверить почту
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authapimodels.SendEmail'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Проверить почту
      tags:
      - Регистрация_организации
  /api/v1/auth/login:
    post:
      description: Аутентификация пользователя
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authapimodels.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apimodels.Response'
            - properties:
                data:
                  $ref: '#/definitions/authapimodels.JWTResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Аутентификация пользователя
      tags:
      - Аутентификация пользователей
  /api/v1/auth/me:
    get:
      description: Получить информацию о текущем пользователе
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/spaceapimodels.SpaceUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Получить информацию о текущем пользователе
      tags:
      - Аутентификация пользователей
  /api/v1/auth/refresh-token:
    post:
      description: Обновить JWT
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authapimodels.JWTRefreshRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apimodels.Response'
            - properties:
                data:
                  $ref: '#/definitions/authapimodels.JWTResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Обновить JWT
      tags:
      - Аутентификация пользователей
  /api/v1/auth/register:
    post:
      description: Отправляет письмо с подтверждением на почту
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authapimodels.SendEmail'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Отправить письмо с подтверждением на почту
      tags:
      - Регистрация_организации
  /api/v1/auth/verify-email:
    get:
      description: Подтверждение почты кодом
      parameters:
      - description: код подтверждения
        in: query
        name: code
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Подтверждение почты кодом
      tags:
      - Регистрация_организации
  /api/v1/organizations:
    post:
      description: Создание организации
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/spaceapimodels.CreateOrganization'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Создание организации
      tags:
      - Организации
  /api/v1/organizations/retrieve:
    post:
      description: Запрос детальной информации через Дадата
      parameters:
      - description: параметры запроса в дадату
        in: query
        name: query
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Запрос детальной информации через Дадата
      tags:
      - Организации
  /api/v1/organizations/suggest:
    get:
      description: Поиск по ИНН через Дадата
      parameters:
      - description: параметры запроса в дадату
        in: query
        name: query
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.Response'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.Response'
      summary: Поиск по ИНН через Дадата
      tags:
      - Организации
swagger: "2.0"
